### ISSUE TITLE
ROUTE_DESC value too long for type character varying (1024)

### ISSUE THREAD

**Issue by wkulesza** [TransitTrack/transittrack#38]
When importing GTFS with a ROUTE_DESC which is long (the GTFS file itself is valid), following error appears:
`Caused by: java.sql.BatchUpdateException: Batch entry 4 insert into routes (color,description,max_lat,max_lon,min_lat,min_lon,hidden,long_name,max_distance,name,route_order,short_name,text_color,type,config_rev,id) values ( [...]
was aborted: ERROR: value too long for type character varying(1024)  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError([BatchResultHandler.java:165](http://batchresulthandler.java:165/))`

**Comment by vesavlad** [comment]
@TsimurSh we should truncate the received route description in order to make sure it fits in what we store in DB. 

Could you please do this fix?

**Comment by TsimurSh** [comment]
Well done
